/**
 * @author yanglei
 * @date 2016-09-18
 * @fileoverview 
 */
module.exports = {
    id : String,
    date : Date,
    day_type : Number,
    plan_type : String,
    rebate_type : String,
    category_id_1 : String,
    category_id_2 : String,
    category_id_3 : String,
    category_id_4 : String,
    unique_plan_id_num : Number,
    unique_order_num : Number,
    unique_is_rebate_order_num : Number,
    unique_user_num : Number,
    unique_is_rebate_user_num : Number,
    unique_shop_num : Number,
    unique_is_rebate_shop_num : Number,
    unique_back_user_num : Number,
    unique_is_rebate_back_user_num : Number,
    unique_back_merchandise_num : Number,
    unique_is_rebate_back_merchandise_num : Number,
    unique_merchandise_num : Number,
    unique_is_rebate_merchandise_num : Number,
    unique_is_over_rebate_order_num : Number,
    unique_expect_rebate_user_num : Number,
    fee : Number,
    is_rebate_fee : Number,
    merchandise_num : Number,
    is_rebate_merchandise_num : Number,
    back_merchandise_num : Number,
    is_rebate_back_merchandise_num : Number,
    back_merchandise_amount : Number,
    is_rebate_back_merchandise_amount : Number,
    cancel_is_rebate_order_num : Number,
    cancel_order_num : Number,
    is_over_rebate_order_amount : Number,
    expect_rebate_amount : Number,
    cancel_rebate_amount : Number,
};